MAXSOURCEDATAROWS = 300
NOMINALSTD = 0.1
OUTLIERCOLOR = (0.5, 0.5, 0.5)

MAXSEARCH = 1
MAXTPATH = 1
MAXTPATHDEPTH = 5
PRUNINGDEPTH = 1
ONLYVISUALIZESELECTIONMATCHINGCHANNELS = True
ONLYNEWTPATH = False
SEPERATION = "<SEPERATION>"
RECOMMENDPCT = 1.0
FLOATCANBEKEY = False
MULTIPROCESS = False
DEBUG = True

MAXSCATTER = 10
MAXLINE = 3
MAXCATLINE = 2
MAXBAR = 4

MAXLINENUMINCHART = 3
MAXBARNUMINCHART = 3

HOST='0.0.0.0'
PORT=23334